default:
	mkdir -p bin

sqInRect:
	gcc -g src/sqInRect/main.c src/sqInRect/sqInRect.c -o bin/sqInRect

longest: 
	gcc -g src/longest/main.c -o bin/longest

water:
	gcc -g src/water/main.c -o bin/water

findsum:
	gcc -g src/findsum/main.c -o bin/findsum

cubePile:
	gcc -g src/cubePile/main.c -o bin/cubePile

sorted:
	gcc -g src/sorted/main.c -o bin/sorted

sort:
	gcc -g -o bin/sort src/sort/main.c -lcriterion

passphrase:
	gcc -g -o bin/passphrase src/passphrase/main.c -lcriterion

salesman:
	gcc -g -o bin/salesman src/salesman/main.c -lcriterion

braking:
	gcc -g -o bin/braking src/braking/main.c -lcriterion
