export const INIT_SOCKET = 'INIT_SOCKET'
export const NEXT_GEN = 'NEXT_GEN'
export const RESYNC = 'RESYNC'
export const DIRT = 'DIRT'
export const SWITCH_CELL = 'SWITCH_CELL'
export const ADD_PATTERN = 'ADD_PATTERN'